import React from "react";
export const languages = [
  {"label": "Afrikaans (South Africa)", "value": "af-ZA"},
  {"label": "Arabic", "value": "ar-XA"},
  {"label": "Basque (Spain)", "value": "eu-ES"},
  {"label": "Bengali (India)", "value": "bn-IN"},
  {"label": "Bulgarian (Bulgaria)", "value": "bg-BG"},
  {"label": "Catalan (Spain)", "value": "ca-ES"},
  {"label": "Chinese (Hong Kong)", "value": "yue-HK"},
  {"label": "Danish (Denmark)", "value": "da-DK"},
  {"label": "Dutch (Belgium)", "value": "nl-BE"},
  {"label": "Dutch (Netherlands)", "value": "nl-NL"},
  {"label": "English (Australia)", "value": "en-AU"},
  {"label": "English (India)", "value": "en-IN"},
  {"label": "English (UK)", "value": "en-GB"},
  {"label": "English (US)", "value": "en-US"},
  {"label": "Filipino (Philippines)", "value": "fil-PH"},
  {"label": "Finnish (Finland)", "value": "fi-FI"},
  {"label": "French (Canada)", "value": "fr-CA"},
  {"label": "French (France)", "value": "fr-FR"},
  {"label": "Galician (Spain)", "value": "gl-ES"},
  {"label": "German (Germany)", "value": "de-DE"},
  {"label": "Greek (Greece)", "value": "el-GR"},
  {"label": "Gujarati (India)", "value": "gu-IN"},
  {"label": "Hebrew (Israel)", "value": "he-IL"},
  {"label": "Hindi (India)", "value": "hi-IN"},
  {"label": "Hungarian (Hungary)", "value": "hu-HU"},
  {"label": "Icelandic (Iceland)", "value": "is-IS"},
  {"label": "Indonesian (Indonesia)", "value": "id-ID"},
  {"label": "Italian (Italy)", "value": "it-IT"},
  {"label": "Japanese (Japan)", "value": "ja-JP"},
  {"label": "Kannada (India)", "value": "kn-IN"},
  {"label": "Korean (South Korea)", "value": "ko-KR"},
  {"label": "Latvian (Latvia)", "value": "lv-LV"},
  {"label": "Lithuanian (Lithuania)", "value": "lt-LT"},
  {"label": "Malay (Malaysia)", "value": "ms-MY"},
  {"label": "Malayalam (India)", "value": "ml-IN"},
  {"label": "Mandarin Chinese", "value": "cmn-CN"},
  {"label": "Mandarin Chinese", "value": "cmn-TW"},
  {"label": "Marathi (India)", "value": "mr-IN"},
  {"label": "Norwegian (Norway)", "value": "nb-NO"},
  {"label": "Polish (Poland)", "value": "pl-PL"},
  {"label": "Portuguese (Brazil)", "value": "pt-BR"},
  {"label": "Portuguese (Portugal)", "value": "pt-PT"},
  {"label": "Punjabi (India)", "value": "pa-IN"},
  {"label": "Romanian (Romania)", "value": "ro-RO"},
  {"label": "Russian (Russia)", "value": "ru-RU"},
  {"label": "Serbian (Cyrillic)", "value": "sr-RS"},
  {"label": "Slovak (Slovakia)", "value": "sk-SK"},
  {"label": "Spanish (Spain)", "value": "es-ES"},
  {"label": "Spanish (US)", "value": "es-US"},
  {"label": "Swedish (Sweden)", "value": "sv-SE"},
  {"label": "Tamil (India)", "value": "ta-IN"},
  {"label": "Telugu (India)", "value": "te-IN"},
  {"label": "Thai (Thailand)", "value": "th-TH"},
  {"label": "Turkish (Turkey)", "value": "tr-TR"},
  {"label": "Ukrainian (Ukraine)", "value": "uk-UA"},
  {"label": "Vietnamese (Vietnam)", "value": "vi-VN"}
]
;
